# Generated by Django 4.2.3 on 2026-03-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('py', 'Python'), ('c', 'C'), ('js', 'JavaScript')], max_length=255, null=True),
        ),
    ]
